### ISSUE TITLE
Suggest wallets via deep linking functionality for mobile browsers

### ISSUE THREAD

**Issue by dmf7z** [dexdexplatform/dexdex-mono#54]
When a user access the widget from mobile browser, instead of the message "You do not have a wallet connected", suggest using one wallet via deep links.

Trust Wallet: https://medium.com/@trustwallet/mobile-dapps-with-deep-linking-and-trust-wallet-6a4712b9b9a4
Status.im: https://get.status.im/browse/easytrade.io

**Comment by mcortesi** [comment]
@sebazelonka we need to style the modal on branch:feat/deep-linking
